### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by pedro-mendonca** [closemarketing/debug-mo-translations#4]
Hi,
Thank you for the plugin, I use many times for debugging purposes!

The plugin output is very simple, would accept some UI improvements suggestions?

Also, would you accept some I18n fixes to allow it to be translatable?

**Comment by davidperezgar** [comment]
Hello! Yes of course I’d glad to receive feedbacks. I always thinking to improve it, but I have no time! Anyway, send me and we could try to make some improvements

**Comment by pedro-mendonca** [comment]
Hi, awesome :)

To start, the hook:
I see you've used the hook `shutdown`, is it to catch all?
I though of moving it into `in_admin_footer`, adding the output above the footer, to inherit the `#wpfooter` CSS (margin-left, etc, for all media queries) and to avoid duplicating the `#wpcontent` ID, but as the footer position is fixed, it will need to set #wpfooter position: relative. The only catch is the footer is hidden on screens < 782px
To output in frontend could be use `wp_footer` hook,

What are your thougths on this?

**Comment by davidperezgar** [comment]
Nice! could you make a PR to develop branch?

**Comment by pedro-mendonca** [comment]
I'll open a PR with this first change, and after that will post here some suggestions for the Admin design.

**Comment by pedro-mendonca** [comment]
@davidperezgar the #6 changes the hook for a cleaner admin output as mentioned above.
For the frontend the output format remains unchanged.

If this is ok, I'll continue with the output itself.

**Comment by davidperezgar** [comment]
Perfect! merged and new version!

**Comment by pedro-mendonca** [comment]
@davidperezgar now I'll suggest some output improvements.

This is the current output:
![imagem](https://user-images.githubusercontent.com/7371591/142190538-8a5e24b4-9365-40c5-bf37-30e5832b971c.png)

Here are 3 suggestions:

1) Simple white background, h3, paragraphs and preformated output
![imagem](https://user-images.githubusercontent.com/7371591/142193987-8a8f737e-6fc4-4852-ac6f-84d3ff0bf3a6.png)

2) Dismissible (or not) footer admin notice with multiple tables
![imagem](https://user-images.githubusercontent.com/7371591/142191106-0beea5d7-ba86-46da-9690-400fdd117e22.png)

3) Dismissible (or not) footer admin notice with one single table
![imagem](https://user-images.githubusercontent.com/7371591/142192611-380a5194-7877-419c-bef4-209b93bf0a64.png)

My preference is the single table in option 3, with stripes every 3 rows. Being an admin notice or just plain white rectangle.
Do you like any of these?

**Comment by davidperezgar** [comment]
Nice suggestions!
I'd suggest better the second option, that you could see the difference with other plugins
