### ISSUE TITLE
Some output improvements

### ISSUE THREAD

**Issue by davidperezgar** [closemarketing/debug-mo-translations#7]
@pedro-mendonca suggests some output improvements.

This is the current output:
![imagem](https://user-images.githubusercontent.com/7371591/142190538-8a5e24b4-9365-40c5-bf37-30e5832b971c.png)

Here are 3 suggestions:

1) Simple white background, h3, paragraphs and preformated output
![imagem](https://user-images.githubusercontent.com/7371591/142193987-8a8f737e-6fc4-4852-ac6f-84d3ff0bf3a6.png)

2) Dismissible (or not) footer admin notice with multiple tables
![imagem](https://user-images.githubusercontent.com/7371591/142191106-0beea5d7-ba86-46da-9690-400fdd117e22.png)

3) Dismissible (or not) footer admin notice with one single table
![imagem](https://user-images.githubusercontent.com/7371591/142192611-380a5194-7877-419c-bef4-209b93bf0a64.png)

My preference is the single table in option 3, with stripes every 3 rows. Being an admin notice or just plain white rectangle.
Do you like any of these?

_Originally posted by @pedro-mendonca in https://github.com/closemarketing/debug-mo-translations/issues/4#issuecomment-971497465_

**Comment by pedro-mendonca** [comment]
As you [liked the second](https://github.com/closemarketing/debug-mo-translations/issues/4#issuecomment-971512485), would you like me to add a PR with it?

I'll add the header as the suggestion 3 for a cleaner separation between plugin title, version and locale.

About the admin notice format, should I keep it dismissible or not? Do you like the simple gray color? Or do you prefer the admin notice blue (notice-info)? Or even polyglots pink :D ?

**Comment by davidperezgar** [comment]
Thanks Pedro. Yes, if you could please PR to the second, it'd be great!

The plugin when is active, it shows this messages. I think is not necessary at all be dismissible. What do you think it would be helpful?

Admin notice blue!!! ;)

**Comment by pedro-mendonca** [comment]
I think we can dismiss the dismissibility :)
Admin blue it is!
Updated the PR #8 (commit https://github.com/closemarketing/debug-mo-translations/pull/8/commits/ec6f3bc678fe65b7c845cbb5deb0deb12f5ae35c)

**Comment by davidperezgar** [comment]
Nice! Released in 1.3!
