### ISSUE TITLE
Self 'debug-mo-translations' entry not shown in the output

### ISSUE THREAD

**Issue by pedro-mendonca** [closemarketing/debug-mo-translations#9]
Hi,
This isn't much important, but might show that something isn't quite right.

To start, the `load_plugin_textdomain()` isn't necessary, since the plugin requires WP 4.6.
Still, even deleting it, the problem persists.
If the `load_plugin_textdomain()` is hooked in `init` it gets shown correctly. Still, many plugins compatible with WP >= 4.6 might have the same issue.
As far as I've seen, only the plugin itself isn't showing on the output.

Is it because loading this plugin textdomain on `plugins_loaded` is too soon to be found by itself? (https://developer.wordpress.org/reference/functions/load_plugin_textdomain/#comment-1568)
If so, then all it will be ok, the `load_plugin_textdomain()` could just be loaded on `init` and it's fine.

**Comment by pedro-mendonca** [comment]
If the problem is the default textdomain load not being able to hook on time so this plugin logs it, then I think it's good to keep the `load_plugin_textdomain()`, loading on `init`.
Either way, despite this issue, Query Monitor always identifies it perfectly, no matter this self capturing issue.

What do you think @davidperezgar?

**Comment by pedro-mendonca** [comment]
Since the issue seems to be the loading of textdomain before the hook, another solution is just move the [`load_plugin_textdomain`](https://github.com/closemarketing/debug-mo-translations/blob/master/debug-mo-translations.php#L39) below the [`override_load_textdomain` filter](https://github.com/closemarketing/debug-mo-translations/blob/master/debug-mo-translations.php#L53).

Either this simple solution or moving it to `init` hook works fine.

**Comment by davidperezgar** [comment]
Ok, we will move to init hook then.

**Comment by davidperezgar** [comment]
Thanks
